### ISSUE TITLE
How does use vary according to data format, file type, data structures, etc. What affects popularity or use within a subject matter?

### ISSUE THREAD

**Issue by JustinGOSSES** [sunlightpolicy/popular-data-sets#9]
Thank you for this work!

My comment is a suggestion, not a problem.

Would love to see this type of analysis but attempt to identify what dataset characteristics had a positive or negative affect within each subject matter domain. 

For example, do certain data formats tend to decrease rate of use or interest? Does CSV perform better than JSON? Is it better to have data definitions in a separate file or the data description? Does number of fields or flat vs. nested data structures matter. 

These types of questions could reveal what to avoid or suggestions of best practice that could drive data owners to transform their data into the most user-friendly format, file type, organization, etc. upon publication.

**Comment by gregjd** [comment]
Great suggestion, that's an interesting question indeed!

(FYI, this research project is no longer ongoing, as it was a particular summer fellow's summer project, but I'm glad you checked it out, and thank you for taking the time to comment!)

**Comment by gregjd** [comment]
And we'd be interested to hear if you ever come across someone else having looked at this question 😄
